language: objective-c
osx_image: xcode12.5

env:
  global:
  - NODE_VERSION=12.18.4

install:

- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- nvm alias default $NODE_VERSION

- brew tap wix/brew
- brew install applesimutils
- yarn

- cd ios && pod install && cd ..

script:
- yarn detox build --configuration ios
- yarn detox test --configuration ios --cleanup

